Art:
  gazebo_ros_control/pid_gains:
    joint_sweeper: {p: 100.0, i: 3.0, d: 1.0}
    joint_foam: {p: 100.0, i: 3.0, d: 1.0}
    joint_servo_gripper: {p: 100.0, i: 3.0, d: 1.0}
    joint_gripper: {p: 100.0, i: 3.0, d: 1.0}
    joint_flap: {p: 100.0, i: 3.0, d: 1.0}
    joint_wheel1: {p: 100.0, i: 3.0, d: 1.0}
    joint_wheel2: {p: 100.0, i: 3.0, d: 1.0}
    joint_gripper_left: {p: 100.0, i: 3.0, d: 1.0}
    joint_gripper_right: {p: 100.0, i: 3.0, d: 1.0}
    joint_gear_left: {p: 100.0, i: 3.0, d: 1.0}
    joint_gear_right: {p: 100.0, i: 3.0, d: 1.0}
  
    